name: Node.js CI

on:
  schedule:
  - cron: "0 0 * * *"


jobs:
  upload:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Upload GPX files
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: yarn run upload
    - name: Verify uploads
      env:
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: yarn test
